# 01 — Array basics

**Workload:** Creation, explicit dtypes, reshape, slicing, fancy indexing, and broadcasting.

This notebook is executed against the RNP engine. Every output below is
stored in the notebook and visible when rendered on GitHub.

In [1]:
from pathlib import Path
import sys

# rnp is the Rust engine's numpy-compatible package: one import swap and
# everything below is ordinary NumPy code.
PROJECT_ROOT = next(
    path for path in (Path.cwd(), *Path.cwd().parents)
    if (path / "shim" / "rnp").is_dir()
)
sys.path.insert(0, str(PROJECT_ROOT / "shim"))

import rnp as np

probe = np.array(0)
print("rnp version:", np.__version__)
print(f"engine: {type(probe).__module__}.{type(probe).__name__}")
assert type(probe).__module__ == "_rnp"

rnp version: 2.5.2
engine: _rnp.ndarray


## Create typed arrays

Build a two-dimensional integer grid and an evenly spaced floating-point vector.

In [2]:
grid = np.arange(12, dtype=np.int64).reshape(3, 4)
unit_interval = np.linspace(0.0, 1.0, 5, dtype=np.float64)
print("grid shape/dtype:", grid.shape, grid.dtype)
print(grid)
print("unit interval:", unit_interval)

grid shape/dtype: (3, 4) int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
unit interval: [0.   0.25 0.5  0.75 1.  ]


## Index and broadcast

Compare basic slicing with paired fancy indices, then broadcast a row across two columns.

In [3]:
sliced = grid[::2, 1::2]
fancy = grid[[2, 0], [1, 3]]
broadcast_sum = grid[:, :2] + np.array([10, 100], dtype=np.int64)
print("slice:", sliced)
print("fancy index:", fancy)
print("broadcast result:\n", broadcast_sum)

slice: [[ 1  3]
 [ 9 11]]
fancy index: [9 3]
broadcast result:
 [[ 10 101]
 [ 14 105]
 [ 18 109]]


## Verify the result

In [4]:
assert np.array_equal(sliced, [[1, 3], [9, 11]])
assert np.array_equal(fancy, [9, 3])
assert np.array_equal(broadcast_sum[-1], [18, 109])
assert np.array_equal(unit_interval, [0.0, 0.25, 0.5, 0.75, 1.0])
print("PASS — all array-basics assertions passed.")

PASS — all array-basics assertions passed.
